"""1_create_models

Revision ID: 0c980e661e85
Revises: 07c71f4389b6
Create Date: 2023-12-05 08:58:47.215552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0c980e661e85"
down_revision = "07c71f4389b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "words",
        sa.Column("word_id", sa.Integer(), nullable=False),
        sa.Column("word", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=50), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("word_id"),
    )
    op.create_table(
        "definitions",
        sa.Column("definition_id", sa.Integer(), nullable=False),
        sa.Column("word_id", sa.Integer(), nullable=True),
        sa.Column("language", sa.String(length=50), nullable=False),
        sa.Column("definition", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["word_id"],
            ["words.word_id"],
        ),
        sa.PrimaryKeyConstraint("definition_id"),
    )
    op.create_table(
        "examples",
        sa.Column("example_id", sa.Integer(), nullable=False),
        sa.Column("word_id", sa.Integer(), nullable=True),
        sa.Column("language", sa.String(length=50), nullable=False),
        sa.Column("example", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["word_id"],
            ["words.word_id"],
        ),
        sa.PrimaryKeyConstraint("example_id"),
    )
    op.create_table(
        "synonyms",
        sa.Column("synonym_id", sa.Integer(), nullable=False),
        sa.Column("word_id", sa.Integer(), nullable=True),
        sa.Column("language", sa.String(length=50), nullable=False),
        sa.Column("synonym", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["word_id"],
            ["words.word_id"],
        ),
        sa.PrimaryKeyConstraint("synonym_id"),
    )
    op.create_table(
        "translations",
        sa.Column("translation_id", sa.Integer(), nullable=False),
        sa.Column("word_id", sa.Integer(), nullable=True),
        sa.Column("language", sa.String(length=50), nullable=False),
        sa.Column("translation", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["word_id"],
            ["words.word_id"],
        ),
        sa.PrimaryKeyConstraint("translation_id"),
    )
    op.drop_index("ix_user_model_email", table_name="user_model")
    op.drop_table("user_model")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_model",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(length=254), autoincrement=False, nullable=False),
        sa.Column(
            "hashed_password",
            sa.VARCHAR(length=128),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="user_model_pkey"),
    )
    op.create_index("ix_user_model_email", "user_model", ["email"], unique=False)
    op.drop_table("translations")
    op.drop_table("synonyms")
    op.drop_table("examples")
    op.drop_table("definitions")
    op.drop_table("words")
    # ### end Alembic commands ###
