"""unique_constraints

Revision ID: 6fdfd6ee975a
Revises: 0c980e661e85
Create Date: 2023-12-09 19:15:52.461150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6fdfd6ee975a"
down_revision = "0c980e661e85"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_model",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("hashed_password", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_model_email"), "user_model", ["email"], unique=True)
    op.create_unique_constraint(
        "_word_language_definition_uc",
        "definitions",
        ["word_id", "language", "definition"],
    )
    op.create_unique_constraint(
        "_word_language_example_uc", "examples", ["word_id", "language", "example"]
    )
    op.create_unique_constraint(
        "_word_language_synonym_uc", "synonyms", ["word_id", "language", "synonym"]
    )
    op.create_unique_constraint(
        "_word_language_translation_uc",
        "translations",
        ["word_id", "language", "translation"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("_word_language_translation_uc", "translations", type_="unique")
    op.drop_constraint("_word_language_synonym_uc", "synonyms", type_="unique")
    op.drop_constraint("_word_language_example_uc", "examples", type_="unique")
    op.drop_constraint("_word_language_definition_uc", "definitions", type_="unique")
    op.drop_index(op.f("ix_user_model_email"), table_name="user_model")
    op.drop_table("user_model")
    # ### end Alembic commands ###
